#!/bin/sh /etc/rc.common
# procd init script for gameboost

USE_PROCD=1
START=99
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh /etc/gameboost/core.sh boot
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    /etc/gameboost/core.sh disable
}

reload_service() {
    /etc/gameboost/core.sh reload
}

service_triggers() {
    procd_add_reload_trigger "gameboost"
}
